<script lang="ts" setup>
import NNTable from "../Table.vue";
import NNTag from "../Tag.vue";

const columns = [
  {
    id: "id",
    label: "ID",
    width: "100px",
  },
  {
    id: "firstName",
    label: "First name",
  },
  {
    id: "lastName",
    label: "Last name",
  },
  {
    id: "email",
    label: "E-Mail",
  },
  {
    id: "country",
    label: "Country",
  },
];

const rows = [
  {
    id: "000001",
    firstName: "Lani",
    lastName: "Ovendale",
    email: "lovendale0@w3.org",
    country: "United Kingdom",
  },
  {
    id: "000002",
    firstName: "Israel",
    lastName: "Tassell",
    email: "itassell1@ow.ly",
    country: "Macedonia",
  },
  {
    id: "000003",
    firstName: "Eveleen",
    lastName: "Mercer",
    email: "emercer2@ow.ly",
    country: "Portugal",
  },
  {
    id: "000004",
    firstName: "Conn",
    lastName: "Whitley",
    email: "cwhitley3@wsj.com",
    country: "Albania",
  },
  {
    id: "000005",
    firstName: "Cherye",
    lastName: "Smitheram",
    email: "csmitheram4@rambler.ru",
    country: "Indonesia",
  },
  {
    id: "000006",
    firstName: "Bunnie",
    lastName: "Sked",
    email: "bsked5@51.la",
    country: "Nigeria",
  },
  {
    id: "000007",
    firstName: "Helaine",
    lastName: "Crother",
    email: "hcrother6@opera.com",
    country: "Philippines",
  },
  {
    id: "000008",
    firstName: "Tana",
    lastName: "Ajean",
    email: "tajean7@sfgate.com",
    country: "China",
  },
  {
    id: "000009",
    firstName: "Sollie",
    lastName: "Greenrde",
    email: "sgreenrde8@wikispaces.com",
    country: "Russia",
  },
  {
    id: "000010",
    firstName: "Vernon",
    lastName: "Millington",
    email: "vmillington9@marketwatch.com",
    country: "Portugal",
  },
  {
    id: "000011",
    firstName: "Willard",
    lastName: "Speares",
    email: "wspearesa@hao123.com",
    country: "China",
  },
  {
    id: "000012",
    firstName: "Minette",
    lastName: "Adderson",
    email: "maddersonb@netlog.com",
    country: "Philippines",
  },
  {
    id: "000013",
    firstName: "Madonna",
    lastName: "Richemont",
    email: "mrichemontc@nasa.gov",
    country: "Pakistan",
  },
  {
    id: "000014",
    firstName: "Osbourne",
    lastName: "Roscoe",
    email: "oroscoed@noaa.gov",
    country: "South Africa",
  },
  {
    id: "000015",
    firstName: "Kath",
    lastName: "Hancock",
    email: "khancocke@earthlink.net",
    country: "Indonesia",
  },
  {
    id: "000016",
    firstName: "Aleta",
    lastName: "Doughartie",
    email: "adoughartief@typepad.com",
    country: "China",
  },
  {
    id: "000017",
    firstName: "Mirilla",
    lastName: "Worland",
    email: "mworlandg@mashable.com",
    country: "Sweden",
  },
  {
    id: "000018",
    firstName: "Jena",
    lastName: "Creddon",
    email: "jcreddonh@bbc.co.uk",
    country: "New Zealand",
  },
  {
    id: "000019",
    firstName: "De witt",
    lastName: "Hellcat",
    email: "dhellcati@microsoft.com",
    country: "Indonesia",
  },
  {
    id: "000020",
    firstName: "Cleon",
    lastName: "Medgwick",
    email: "cmedgwickj@livejournal.com",
    country: "China",
  },
  {
    id: "000021",
    firstName: "Caressa",
    lastName: "Aberchirder",
    email: "caberchirderk@mit.edu",
    country: "France",
  },
  {
    id: "000022",
    firstName: "Dona",
    lastName: "Hindrich",
    email: "dhindrichl@google.com",
    country: "United States",
  },
  {
    id: "000023",
    firstName: "Eryn",
    lastName: "Urrey",
    email: "eurreym@apache.org",
    country: "Indonesia",
  },
  {
    id: "000024",
    firstName: "Chelsea",
    lastName: "Wildgoose",
    email: "cwildgoosen@behance.net",
    country: "Philippines",
  },
  {
    id: "000025",
    firstName: "Edd",
    lastName: "Leffek",
    email: "eleffeko@msn.com",
    country: "China",
  },
  {
    id: "000026",
    firstName: "Nicol",
    lastName: "Le Barr",
    email: "nlebarrp@cocolog-nifty.com",
    country: "Belarus",
  },
  {
    id: "000027",
    firstName: "Vonnie",
    lastName: "McGonigle",
    email: "vmcgonigleq@youku.com",
    country: "Albania",
  },
  {
    id: "000028",
    firstName: "Daffie",
    lastName: "Suche",
    email: "dsucher@wikia.com",
    country: "Indonesia",
  },
  {
    id: "000029",
    firstName: "Shirlene",
    lastName: "Simper",
    email: "ssimpers@imageshack.us",
    country: "Paraguay",
  },
  {
    id: "000030",
    firstName: "Sasha",
    lastName: "Huddles",
    email: "shuddlest@amazon.de",
    country: "Nigeria",
  },
  {
    id: "000031",
    firstName: "Derby",
    lastName: "Basler",
    email: "dbasleru@soundcloud.com",
    country: "Laos",
  },
  {
    id: "000032",
    firstName: "Ricoriki",
    lastName: "Sykora",
    email: "rsykorav@tuttocitta.it",
    country: "China",
  },
  {
    id: "000033",
    firstName: "Sidney",
    lastName: "Sargison",
    email: "ssargisonw@businessinsider.com",
    country: "Italy",
  },
  {
    id: "000034",
    firstName: "Aleece",
    lastName: "Reilingen",
    email: "areilingenx@mlb.com",
    country: "France",
  },
  {
    id: "000035",
    firstName: "Hieronymus",
    lastName: "Bernardin",
    email: "hbernardiny@hud.gov",
    country: "Burkina Faso",
  },
  {
    id: "000036",
    firstName: "Shara",
    lastName: "Mindenhall",
    email: "smindenhallz@nifty.com",
    country: "Philippines",
  },
  {
    id: "000037",
    firstName: "Rodney",
    lastName: "Everington",
    email: "reverington10@people.com.cn",
    country: "Czech Republic",
  },
  {
    id: "000038",
    firstName: "Calvin",
    lastName: "Marke",
    email: "cmarke11@prweb.com",
    country: "Tuvalu",
  },
  {
    id: "000039",
    firstName: "Daloris",
    lastName: "Scandrite",
    email: "dscandrite12@java.com",
    country: "Canada",
  },
  {
    id: "000041",
    firstName: "Linnea",
    lastName: "Gillingwater",
    email: "lgillingwater14@tamu.edu",
    country: "Israel",
  },
  {
    id: "000042",
    firstName: "Tina",
    lastName: "Jentle",
    email: "tjentle15@walmart.com",
    country: "Portugal",
  },
  {
    id: "000043",
    firstName: "Waiter",
    lastName: "Boydle",
    email: "wboydle16@wired.com",
    country: "Ukraine",
  },
  {
    id: "000044",
    firstName: "Nydia",
    lastName: "Pescott",
    email: "npescott17@blogs.com",
    country: "Japan",
  },
  {
    id: "000045",
    firstName: "Birch",
    lastName: "Sergent",
    email: "bsergent18@youtube.com",
    country: "France",
  },
  {
    id: "000046",
    firstName: "Fran",
    lastName: "Belvard",
    email: "fbelvard19@archive.org",
    country: "Togo",
  },
  {
    id: "000047",
    firstName: "Aurie",
    lastName: "Bills",
    email: "abills1a@ask.com",
    country: "Russia",
  },
  {
    id: "000048",
    firstName: "Aundrea",
    lastName: "O' Connell",
    email: "aoconnell1b@va.gov",
    country: "El Salvador",
  },
  {
    id: "000049",
    firstName: "Florenza",
    lastName: "Fevers",
    email: "ffevers1c@tumblr.com",
    country: "Madagascar",
  },
  {
    id: "000050",
    firstName: "Urbano",
    lastName: "Baudinelli",
    email: "ubaudinelli1d@scribd.com",
    country: "China",
  },
  {
    id: "000051",
    firstName: "Leonelle",
    lastName: "Stolte",
    email: "lstolte1e@marketwatch.com",
    country: "Indonesia",
  },
  {
    id: "000052",
    firstName: "Georgiana",
    lastName: "Yashanov",
    email: "gyashanov1f@theatlantic.com",
    country: "Indonesia",
  },
  {
    id: "000053",
    firstName: "Carly",
    lastName: "Foottit",
    email: "cfoottit1g@deviantart.com",
    country: "Indonesia",
  },
  {
    id: "000054",
    firstName: "Frans",
    lastName: "Teas",
    email: "fteas1h@utexas.edu",
    country: "Russia",
  },
  {
    id: "000055",
    firstName: "Joice",
    lastName: "Gate",
    email: "jgate1i@economist.com",
    country: "United States",
  },
  {
    id: "000056",
    firstName: "Merilee",
    lastName: "Winsom",
    email: "mwinsom1j@nationalgeographic.com",
    country: "Japan",
  },
  {
    id: "000057",
    firstName: "Fannie",
    lastName: "Tummasutti",
    email: "ftummasutti1k@dion.ne.jp",
    country: "Japan",
  },
  {
    id: "000058",
    firstName: "Pete",
    lastName: "Kerner",
    email: "pkerner1l@youku.com",
    country: "Russia",
  },
  {
    id: "000059",
    firstName: "Skip",
    lastName: "Wilne",
    email: "swilne1m@alexa.com",
    country: "Indonesia",
  },
  {
    id: "000061",
    firstName: "Katti",
    lastName: "Jacobbe",
    email: "kjacobbe1o@wikia.com",
    country: "Poland",
  },
  {
    id: "000062",
    firstName: "Giraud",
    lastName: "McAlarney",
    email: "gmcalarney1p@nyu.edu",
    country: "Canada",
  },
  {
    id: "000063",
    firstName: "Wyatan",
    lastName: "Josuweit",
    email: "wjosuweit1q@rambler.ru",
    country: "Canada",
  },
  {
    id: "000064",
    firstName: "Xaviera",
    lastName: "Gilder",
    email: "xgilder1r@bravesites.com",
    country: "United States",
  },
  {
    id: "000066",
    firstName: "Mariana",
    lastName: "Sidden",
    email: "msidden1t@harvard.edu",
    country: "Philippines",
  },
  {
    id: "000067",
    firstName: "Roi",
    lastName: "Behning",
    email: "rbehning1u@discuz.net",
    country: "Japan",
  },
  {
    id: "000068",
    firstName: "Fransisco",
    lastName: "Phelit",
    email: "fphelit1v@networkadvertising.org",
    country: "Russia",
  },
  {
    id: "000069",
    firstName: "Zonnya",
    lastName: "Shwenn",
    email: "zshwenn1w@usatoday.com",
    country: "Indonesia",
  },
  {
    id: "000070",
    firstName: "Nadiya",
    lastName: "Zum Felde",
    email: "nzumfelde1x@cdc.gov",
    country: "Belarus",
  },
  {
    id: "000071",
    firstName: "Rickie",
    lastName: "Laydel",
    email: "rlaydel1y@nytimes.com",
    country: "China",
  },
  {
    id: "000072",
    firstName: "Bartel",
    lastName: "Chadwen",
    email: "bchadwen1z@google.ca",
    country: "Albania",
  },
  {
    id: "000073",
    firstName: "Bili",
    lastName: "Devanny",
    email: "bdevanny20@deliciousdays.com",
    country: "Vietnam",
  },
  {
    id: "000074",
    firstName: "Gonzales",
    lastName: "Beaty",
    email: "gbeaty21@istockphoto.com",
    country: "China",
  },
  {
    id: "000075",
    firstName: "Guy",
    lastName: "Sporrij",
    email: "gsporrij22@economist.com",
    country: "Thailand",
  },
  {
    id: "000076",
    firstName: "Valdemar",
    lastName: "Kelberman",
    email: "vkelberman23@jalbum.net",
    country: "Poland",
  },
  {
    id: "000077",
    firstName: "Fletch",
    lastName: "Meneghelli",
    email: "fmeneghelli24@google.com.au",
    country: "Russia",
  },
  {
    id: "000078",
    firstName: "Adel",
    lastName: "Lansberry",
    email: "alansberry25@tripadvisor.com",
    country: "Colombia",
  },
  {
    id: "000079",
    firstName: "Vernon",
    lastName: "Maulkin",
    email: "vmaulkin26@va.gov",
    country: "China",
  },
  {
    id: "000080",
    firstName: "Kennett",
    lastName: "Goldston",
    email: "kgoldston27@usatoday.com",
    country: "Brazil",
  },
  {
    id: "000081",
    firstName: "Malchy",
    lastName: "Gillitt",
    email: "mgillitt28@drupal.org",
    country: "Russia",
  },
  {
    id: "000082",
    firstName: "Cletis",
    lastName: "Harring",
    email: "charring29@prweb.com",
    country: "Portugal",
  },
  {
    id: "000083",
    firstName: "Avigdor",
    lastName: "Brede",
    email: "abrede2a@liveinternet.ru",
    country: "Indonesia",
  },
  {
    id: "000084",
    firstName: "Brand",
    lastName: "Bartos",
    email: "bbartos2b@ca.gov",
    country: "Greece",
  },
  {
    id: "000085",
    firstName: "Auria",
    lastName: "Dornan",
    email: "adornan2c@google.cn",
    country: "Comoros",
  },
  {
    id: "000086",
    firstName: "Kiley",
    lastName: "Asaaf",
    email: "kasaaf2d@wix.com",
    country: "Venezuela",
  },
  {
    id: "000087",
    firstName: "Angel",
    lastName: "Drinan",
    email: "adrinan2e@ow.ly",
    country: "China",
  },
  {
    id: "000088",
    firstName: "Trey",
    lastName: "Garlick",
    email: "tgarlick2f@stumbleupon.com",
    country: "Colombia",
  },
  {
    id: "000089",
    firstName: "Albertine",
    lastName: "Lowre",
    email: "alowre2g@hud.gov",
    country: "Czech Republic",
  },
  {
    id: "000090",
    firstName: "Adriena",
    lastName: "Shoppee",
    email: "ashoppee2h@si.edu",
    country: "Indonesia",
  },
  {
    id: "000091",
    firstName: "Reg",
    lastName: "Attwooll",
    email: "rattwooll2i@vimeo.com",
    country: "China",
  },
  {
    id: "000092",
    firstName: "Tess",
    lastName: "Giovanetti",
    email: "tgiovanetti2j@usatoday.com",
    country: "Ukraine",
  },
  {
    id: "000093",
    firstName: "Trix",
    lastName: "Boddie",
    email: "tboddie2k@stumbleupon.com",
    country: "Greece",
  },
  {
    id: "000094",
    firstName: "Kelsy",
    lastName: "Sidgwick",
    email: "ksidgwick2l@newyorker.com",
    country: "Sweden",
  },
  {
    id: "000095",
    firstName: "Brit",
    lastName: "Camelia",
    email: "bcamelia2m@51.la",
    country: "Malaysia",
  },
  {
    id: "000096",
    firstName: "Shelby",
    lastName: "Jays",
    email: "sjays2n@cbc.ca",
    country: "Sweden",
  },
  {
    id: "000097",
    firstName: "Crosby",
    lastName: "Marron",
    email: "cmarron2o@stumbleupon.com",
    country: "United States",
  },
  {
    id: "000098",
    firstName: "Betteanne",
    lastName: "Cornick",
    email: "bcornick2p@theatlantic.com",
    country: "Sweden",
  },
  {
    id: "000099",
    firstName: "Quintana",
    lastName: "Ithell",
    email: "qithell2q@hud.gov",
    country: "Uzbekistan",
  },
  {
    id: "000100",
    firstName: "Tyrus",
    lastName: "Dealey",
    email: "tdealey2r@oaic.gov.au",
    country: "United States",
  },
];
</script>

<template>
  <Story title="Components/Table" :layout="{ type: 'single' }">
    <Variant title="Default">
      <NNTable :columns="columns" :rows="rows" style="max-height: 70vh">
        <template #header-id>#</template>
        <template #cell-id="{ row }">
          <NNTag size="small">
            {{ row["id"] }}
          </NNTag>
        </template>
      </NNTable>
    </Variant>
  </Story>
</template>
